Stores ES document and makes it available on `/data` endpoint
elastic/mock-es pull request #11
Opened 2024-12-31 07:34 UTC by khushijain21

Sample Scenario of its working

- Create a `bulk.json` file
```
{ "index" : { "_index" : "test", "_id" : "1" } }
{ "field1" : "value1" }
{ "delete" : { "_index" : "test", "_id" : "2" } }
{ "create" : { "_index" : "test", "_id" : "3" } }
{ "field1" : "value3" }
{ "update" : {"_id" : "1", "_index" : "test"} }
{ "doc" : {"field2" : "value2"} }
```

- Install and start the server

```
go install ./cmd/mock-es 
mock-es
```

- Send a POST bulk request

```
curl -X POST "http://localhost:9200/_bulk" -H "Content-Type: application/json" --data-binary @bulk.json
```

- Send a GET request on `/data` endpoint

``` 
curl localhost:9200/data
```

And our response will include the data stored

```
{"test":{"1":{"field1":"value1"},"3":{"field1":"value3"}}}%  
```

2025-01-02 11:08 UTC, mauri870 commented
@khushijain21 What is the use case for this feature? Could you elaborate on it? Thanks!

2025-01-02 11:20 UTC, mauri870 commented on pkg/api/api.go
> +var doc dataStore = dataStore{data: make(map[string]map[string]map[string]any)}
Reads and writes to this variable can occur in parallel by multiple requests, so you would need a mutex to serialize access.

2025-01-02 18:39 UTC, leehinman requested changes
I have some concerns.

First with the current implementation it looks like every doc is going to be stored in memory, with no limits.  That kills one of the primary use cases for mock-es which is to just consume and discard the data.  

Second, this is pulling documents from the bulk request and trying to do updates/deletes etc.  If you really need to test for this, you should be using the real elasticsearch.

Third, if we really do want to save data that is sent to mock-es, I would prefer that we save a copy of the whole request or maybe request body.  And this needs to be some kind of circular buffer where we only store the last 10 or so requests.  And we need a way to opt in or out of this behavior.

2025-01-03 11:37 UTC, mauri870 commented
I agree with Lee; it seems like we're trying to implement a makeshift version of Elasticsearch. I believe the main use case is debugging the requests, so perhaps saving just the request body is sufficient for now.

2025-01-06 11:36 UTC, mauri870 commented
I spoke with Khushi and we agreed that I will take over this task to implement saving the request body instead. I will open a separate PR for it.

2025-01-06 11:36 UTC, closed without merging